---
title: "hoff_chp_4"
author: "Elliot Pickens"
date: '2022-10-12'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

# 4.2

```{r}
gamma_a = c(120, 10)
gamma_b = c(12, 1)

a = c(12,9,12,14,13,13,15,8,15,6)
b = c(11,11,10,9,9,8,7,10,6,8,8,9,7)


theta.mc = rgamma ( 10000 , gamma_a[1]+sum(a), gamma_a[2]+length(a) )
theta2.mc = rgamma ( 10000 , gamma_b[1]+sum(b) , gamma_b[2]+length(b))
mean(theta.mc>theta2.mc)

for (i in 1:10) {
  
  theta.mc = rgamma ( 10000 , gamma_a[1]+sum(a), gamma_a[2]+length(a) )
  theta2.mc = rgamma ( 10000 , i*gamma_b[1]+sum(b) , i*gamma_b[2]+length(b))
  print(mean(theta.mc>theta2.mc))
  
}

theta.mc = rgamma ( 10000 , gamma_a[1]+sum(a), gamma_a[2]+length(a) )
theta2.mc = rgamma ( 10000 , gamma_b[1]+sum(b) , gamma_b[2]+length(b))
y1.mc = rpois(10000, theta.mc)
y2.mc = rpois(10000, theta2.mc)
mean(y1.mc>y2.mc)

for (i in 1:10) {
  theta.mc = rgamma ( 10000 , i*gamma_a[1]+sum(a), gamma_a[2]+length(a) )
  theta2.mc = rgamma ( 10000 , i*gamma_b[1]+sum(b) , gamma_b[2]+length(b))
  y1.mc = rpois(10000, theta.mc)
  y2.mc = rpois(10000, theta2.mc)
  print(mean(y1.mc>y2.mc))
}

```

```{r}
avgs_a = rep(0, 1000)
sds_a = rep(0, 1000)
avgs_b = rep(0, 1000)
sds_b = rep(0, 1000)

for (i in 1:1000) {
  theta.mc = rgamma ( 1 , gamma_a[1]+sum(a), gamma_a[2]+length(a) )
  theta2.mc = rgamma ( 1 , gamma_b[1]+sum(b) , gamma_b[2]+length(b))
  y1.mc = rpois(10, theta.mc)
  y2.mc = rpois(10, theta2.mc)
  avgs_a[i] = mean(y1.mc)
  sds_a[i] = sd(y1.mc)
  avgs_b[i] = mean(y2.mc)
  sds_b[i] = sd(y2.mc)
}

avgs_a %>% data.frame() %>% 
  ggplot(aes(x=avgs_a)) + 
  geom_bar() +
  geom_vline(xintercept = mean(a), size=2, linetype="dashed") +
  ggtitle("A Avg Check")

avgs_b %>% data.frame() %>% 
  ggplot(aes(x=avgs_a)) + 
  geom_bar() +
  geom_vline(xintercept = mean(b), size=2, linetype="dashed") +
  ggtitle("B Avg Check")

sds_a %>% data.frame() %>% 
  ggplot(aes(x=sds_a)) + 
  geom_bar(width=0.04) +
  geom_vline(xintercept = sd(a), size=2, linetype="dashed") +
  ggtitle("A SD Check")

sds_b %>% data.frame() %>% 
  ggplot(aes(x=sds_b)) + 
  geom_bar(width=0.04) +
  geom_vline(xintercept = sd(b), size=2, linetype="dashed") +
  ggtitle("B SD Check")

```


